In [1]:
#numerical python
#n dimensional array
#applications in computer vision

In [3]:
import numpy as np

In [5]:
a1=np.array([1,2,3,4,5])

In [7]:
a1

array([1, 2, 3, 4, 5])

In [9]:
type(a1)


numpy.ndarray

In [19]:
a2=np.array([[1,2],[3,4]])

In [21]:
a2

array([[1, 2],
       [3, 4]])

In [23]:
type(a2)


numpy.ndarray

In [25]:
a2[0]

array([1, 2])

In [27]:
a2[0][1]

2

In [35]:
a2=np.array([2,3,5,7])

In [37]:
a2

array([2, 3, 5, 7])

In [39]:
a2=np.array([2,3,5,7,9.2])

In [41]:
a2

array([2. , 3. , 5. , 7. , 9.2])

In [43]:
a3=np.array([2,3,4,56,77,1,4],ndmin=5)

In [45]:
a3

array([[[[[ 2,  3,  4, 56, 77,  1,  4]]]]])

In [47]:
a3[0]

array([[[[ 2,  3,  4, 56, 77,  1,  4]]]])

In [49]:
a3[1]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [51]:
a3[0][0]

array([[[ 2,  3,  4, 56, 77,  1,  4]]])

In [53]:
a3[0][0][0]

array([[ 2,  3,  4, 56, 77,  1,  4]])

In [55]:
a4=np.array([2,3,4,56,77,1,4])

In [57]:
a4

array([ 2,  3,  4, 56, 77,  1,  4])

In [59]:
np.asarray([ 2,  3,  4, 56, 77,  1,  4])

array([ 2,  3,  4, 56, 77,  1,  4])

In [61]:
np.asanyarray([ 2,  3,  4, 56, 77,  1,  4])

array([ 2,  3,  4, 56, 77,  1,  4])

In [63]:
np.mat([1,2,3,4,5,6,7])

matrix([[1, 2, 3, 4, 5, 6, 7]])

In [65]:
a=[1,2,3,4,5]
np.asarray(a)


array([1, 2, 3, 4, 5])

In [67]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [69]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [71]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [73]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [75]:
type(np.asanyarray(np.mat(a))) #type=matrix


numpy.matrix

In [81]:
type(np.asarray(np.mat(a)))  #type=n-d array

numpy.ndarray

In [83]:
np.fromfunction(lambda i,j : i==j, (3,3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [85]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [91]:
q1=np.fromfunction(lambda i,j : i*j, (100,100), dtype=int)

In [93]:
q1.ndim

2

In [95]:
q1.size

10000

In [97]:
q1.shape

(100, 100)

In [103]:
np.random.rand(6,5,3) #no of arrays, rows, cols (3 d array)

array([[[0.77624403, 0.75523716, 0.4009592 ],
        [0.3014279 , 0.9679964 , 0.2886582 ],
        [0.79410651, 0.10483433, 0.83003772],
        [0.65278308, 0.26698382, 0.3788937 ],
        [0.45822141, 0.98162732, 0.30446721]],

       [[0.60182871, 0.51417273, 0.22529808],
        [0.73689611, 0.41957828, 0.02950072],
        [0.60323208, 0.01557939, 0.52042306],
        [0.26649276, 0.47396658, 0.19906299],
        [0.34241235, 0.7376036 , 0.50794629]],

       [[0.94356702, 0.36168121, 0.40241837],
        [0.05082134, 0.33761671, 0.02444069],
        [0.76728053, 0.50125887, 0.40617507],
        [0.80651518, 0.22853658, 0.06355739],
        [0.72804549, 0.70461894, 0.56044935]],

       [[0.10863115, 0.5912469 , 0.06378128],
        [0.8848527 , 0.77513092, 0.23965602],
        [0.24595455, 0.84960171, 0.25612664],
        [0.90865457, 0.88254414, 0.18914656],
        [0.3338639 , 0.97395459, 0.45037894]],

       [[0.49076707, 0.99579802, 0.99984939],
        [0.24113951, 0.012

In [111]:
np.random.randint(2,55)

2

In [113]:
import pandas as pd

In [117]:
pd.DataFrame(np.random.randn(6,7))

0         1         2         3         4         5         6
0  1.396681  0.220819 -0.570537  0.721837  1.815347 -0.401047  0.413282
1 -1.691015  0.694981  0.138330  1.033354 -0.105856  0.544041  0.064376
2 -0.169754 -0.965083  0.761248 -2.825709 -0.646932  0.712616 -0.759383
3  1.075669 -1.271592  1.583009 -1.523138  0.502320  1.202676  0.452310
4  0.473457 -0.266472  0.629147  0.027398  1.108788 -1.039613 -1.186584
5  0.707319  0.315896 -0.675930 -0.612367 -0.346177  0.490147  0.443197

In [123]:
a1=np.arange(2,10,0.5) #0.5 is the step size

In [125]:
a1=np.arange(2,10)

In [127]:
a1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
a1[2:7]

array([4, 5, 6, 7, 8])

In [133]:
arr1=np.random.rand(4,5)

In [135]:
arr1

array([[0.22977543, 0.06119812, 0.37153447, 0.76827547, 0.2139548 ],
       [0.16491958, 0.89144624, 0.51068197, 0.87046801, 0.15405838],
       [0.63569576, 0.61122752, 0.83786802, 0.26577906, 0.57783974],
       [0.98638112, 0.61478346, 0.21741189, 0.12569169, 0.31075413]])

In [137]:
arr1[arr1>0.5]

array([0.76827547, 0.89144624, 0.51068197, 0.87046801, 0.63569576,
       0.61122752, 0.83786802, 0.57783974, 0.98638112, 0.61478346])

In [139]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [141]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
np.zeros((5,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [145]:
10 + np.zeros((3,4))

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [147]:
np.empty((5,5))

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.15710088e-306, 6.23056330e-307,
        1.60219578e-306, 7.56601165e-307],
       [6.23061763e-307, 9.34607074e-307, 8.90098127e-307,
        1.11260755e-306, 1.42417629e-306],
       [2.22523140e-306, 1.33511018e-306, 2.22519880e-306,
        2.29179075e-312, 3.49698923e-317]])

In [149]:
np.linspace(4,15)

array([ 4.        ,  4.2244898 ,  4.44897959,  4.67346939,  4.89795918,
        5.12244898,  5.34693878,  5.57142857,  5.79591837,  6.02040816,
        6.24489796,  6.46938776,  6.69387755,  6.91836735,  7.14285714,
        7.36734694,  7.59183673,  7.81632653,  8.04081633,  8.26530612,
        8.48979592,  8.71428571,  8.93877551,  9.16326531,  9.3877551 ,
        9.6122449 ,  9.83673469, 10.06122449, 10.28571429, 10.51020408,
       10.73469388, 10.95918367, 11.18367347, 11.40816327, 11.63265306,
       11.85714286, 12.08163265, 12.30612245, 12.53061224, 12.75510204,
       12.97959184, 13.20408163, 13.42857143, 13.65306122, 13.87755102,
       14.10204082, 14.32653061, 14.55102041, 14.7755102 , 15.        ])

In [151]:
np.linspace(4,15).size

50

In [157]:
np.linspace(1,10, endpoint=False, retstep = True)

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]),
 0.18)

In [159]:
np.logspace(2,10,4,base=2)

array([   4.        ,   25.39841683,  161.26989439, 1024.        ])